name: mwaslaty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  provider: ^6.1.1
  http:
  dartz: ^0.10.1
  audioplayers:
  syncfusion_flutter_pdfviewer: ^24.1.44
  connectivity_checker: ^1.1.0
  flutter_native_splash: ^2.3.9
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter_native_splash:
  android: false
  ios: false
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/soura_quran/
    - assets/hadeth/
    - assets/images/
    - assets/stories/

  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/title.otf
    - family: font2
      fonts:
        - asset: assets/fonts/categories.otf
    - family: font3
      fonts:
        - asset: assets/fonts/font3.ttf
    - family: quran
      fonts:
        - asset: assets/fonts/quran.ttf
    - family: soura
      fonts:
        - asset: assets/fonts/soura.ttf